mixed_list = ["Muhammed", 19, 85.4, True]
mixed_list.append(["Eray", 20, 67.3, False])
print(f"mixed_list = {mixed_list}")
print(f"mixed_list[0] = {mixed_list[0]}")
print(f"type({mixed_list[0]}) = {type(mixed_list[0])}")
print(f"mixed_list[1] = {mixed_list[1]}")
print(f"type({mixed_list[1]}) = {type(mixed_list[1])}")
print(f"mixed_list[2] = {mixed_list[2]}")
print(f"type({mixed_list[2]}) = {type(mixed_list[2])}")
print(f"mixed_list[3] = {mixed_list[3]}")
print(f"type({mixed_list[3]}) = {type(mixed_list[3])}")
print(f"mixed_list[4] = {mixed_list[4]}")
print(f"type({mixed_list[4]}) = {type(mixed_list[4])}")
# listenin son elemanı olan listede 67.3'e erişmek istiyoruz
print(f"mixed_list[-1][2] = {mixed_list[-1][2]}")