names = ["Abdirahim", "Manuel", "Ziya", "İbrahim"]
print(f"names = {names}")
print("Listenin sonuna yeni bir isim ekleyelim:")
names.append("Jesuno")
print(f"names = {names}")
print("Listenin sonuna bir isim daha ekleyelim:")
names.append("Abdullah")
print(f"names = {names}")
print("Listenin başına yeni bir isim ekleyelim:")
names.insert(0, "Bonaventura")
print(f"names = {names}")
print("Listenin başından ikinci sıraya yeni bir isim ekleyelim:")
names.insert(1, "Willy")
print(f"names = {names}")
print("Listenin başından üçüncü sıradaki ismi silelim:")
names.pop(2)
print(f"names = {names}")
print("Listenin başından beşinci ismi silelim:")
names.remove(names[4])
print(f"names = {names}")